In [2]:
import pandas as pd
import numpy as np

In [4]:
items=pd.read_csv('clean_output_user_items.csv')
reviews=pd.read_csv('clean_output_user_reviews.csv')
games=pd.read_csv('clean_output_steam_games.csv')

In [17]:
games.head()

,title,id,developer,Action,Adventure,Animation &amp; Modeling,Audio Production,Casual,Design &amp; Illustration,Early Access,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,Lost Summoner Kitty,761140.0,Kotoshiro,1,0,0,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
1,Ironbound,643980.0,Secret Level SRL,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,Real Pool 3D - Poolians,670290.0,Poolians.com,0,0,0,0,1,0,0,...,0,0,0,1,0,1,0,0,0,0
3,弹炸人2222,767400.0,彼岸领域,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Battle Royale Trainer,772540.0,Trickjump Games Ltd,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [18]:
items.head()

             user_id  item_id                  item_name  playtime_forever
0  76561197970982479       10             Counter-Strike               6.0
1  76561197970982479       20      Team Fortress Classic               0.0
2  76561197970982479       30              Day of Defeat               7.0
3  76561197970982479       40         Deathmatch Classic               0.0
4  76561197970982479       50  Half-Life: Opposing Force               0.0

In [19]:
id_buscado = 10

# Filtra el DataFrame para obtener el nombre del juego con el ID específico
nombre_del_juego = games.loc[games['id'] == id_buscado, 'title'].iloc[0]

# Imprime el nombre del juego
print(nombre_del_juego)

Counter-Strike

In [22]:
maindf=pd.merge(items,games,how='outer',left_on='item_id',right_on='id')

In [25]:
maindf

,user_id,item_id,item_name,playtime_forever,title,id,developer,Action,Adventure,Animation &amp; Modeling,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,76561197970982479,10.0,Counter-Strike,6.0,Counter-Strike,10.0,Valve,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,js41637,10.0,Counter-Strike,0.0,Counter-Strike,10.0,Valve,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Riot-Punch,10.0,Counter-Strike,0.0,Counter-Strike,10.0,Valve,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,doctr,10.0,Counter-Strike,93.0,Counter-Strike,10.0,Valve,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,corrupted_soul,10.0,Counter-Strike,108.0,Counter-Strike,10.0,Valve,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167466,NaN,NaN,NaN,NaN,Kebab it Up!,745400.0,Bidoniera Games,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5167467,NaN,NaN,NaN,NaN,Colony On Mars,773640.0,"Nikita ""Ghost_RUS""",0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
5167468,NaN,NaN,NaN,NaN,LOGistICAL: South Africa,733530.0,Sacada,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5167469,NaN,NaN,NaN,NaN,Russian Roads,610660.0,Laush Dmitriy Sergeevich,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5167470,NaN,NaN,NaN,NaN,EXIT 2 - Directions,658870.0,"xropi,stev3ns",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
maindf1=maindf.dropna(axis=0,how='any')
maindf1.reset_index(inplace=True)
maindf1.drop(['item_id','item_name','index'],axis=1,inplace=True)

In [43]:
maindf1.to_csv('maindb.csv',index=False)

In [6]:
alldb=pd.read_csv('maindb.csv')

In [ ]:
alldb['release_date']=pd.to_datetime(alldb['release_date'])

In [75]:
alldb['release_year'] = alldb['release_date'].str.extract(r'(\d{4})', expand=False)

In [84]:
alldb

,user_id,playtime_forever,title,id,developer,release_year,Action,Adventure,Animation &amp; Modeling,Audio Production,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,76561197970982479,6.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,js41637,0.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Riot-Punch,0.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,doctr,93.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,corrupted_soul,108.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4039495,peter1023199,6.0,DUCATI - 90th Anniversary,456780.0,Milestone S.r.l.,2016.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4039496,76561198071808318,46.0,Mimpi Dreams,444770.0,Silicon Jelly,2016.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4039497,76561198081168593,51.0,NOBUNAGA'S AMBITION: Sphere of Influence - Asc...,375450.0,"KOEI TECMO GAMES CO., LTD.",2016.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4039498,76561198107283457,164.0,ChaosTower,354280.0,CashcowGames,2016.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4039499,inven,0.0,Aveyond 4: Shadow of the Mist,433920.0,"Amaranth Games, LLC",2016.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [107]:
genero='action'
genero=genero.capitalize()
genero_db=alldb[alldb[genero]==1]
playtime_db=genero_db.groupby('release_year')['playtime_forever'].sum().reset_index()
max_playtime_year= playtime_db.loc[playtime_db['playtime_forever'].idxmax(),'release_year']
print(f'El año de lanzamiento con más horas jugadas para el género de {genero} fue el: {max_playtime_year}')

El año de lanzamiento con más horas jugadas para el género de Action fue el: 2012.0

In [166]:
genre='action'
genre=genre.capitalize()
genre_db=alldb[alldb[genre]==1]
playtime_user=genre_db.groupby(['user_id'])['playtime_forever'].sum().reset_index()
playtime_db=genre_db.groupby(['user_id','release_year'])['playtime_forever'].sum().reset_index()
max_playtime_user=playtime_user.loc[playtime_user['playtime_forever'].idxmax(),'user_id']
playtime_db1=playtime_db[playtime_db['user_id']==max_playtime_user]
listtime=[]
for i, row in playtime_db1.iterrows(): 
    listtime.append(['Year:', row['release_year'],'Time played', row['playtime_forever']])
print(f'The player with the most hours played in genre: {genero} was: {max_playtime_user} with the following split: {listtime}')

The player with the most hours player in genre: Action was: Sp3ctre with the following split: [['Year:', 1993.0, 'Time played', 0.0], ['Year:', 1995.0, 'Time played', 217.0], ['Year:', 1996.0, 'Time played', 0.0], ['Year:', 1998.0, 'Time played', 0.0], ['Year:', 1999.0, 'Time played', 44.0], ['Year:', 2000.0, 'Time played', 70644.0], ['Year:', 2001.0, 'Time played', 13.0], ['Year:', 2002.0, 'Time played', 238.0], ['Year:', 2003.0, 'Time played', 7673.0], ['Year:', 2004.0, 'Time played', 127411.0], ['Year:', 2005.0, 'Time played', 21339.0], ['Year:', 2006.0, 'Time played', 896.0], ['Year:', 2007.0, 'Time played', 112784.0], ['Year:', 2008.0, 'Time played', 224.0], ['Year:', 2009.0, 'Time played', 108326.0], ['Year:', 2010.0, 'Time played', 78083.0], ['Year:', 2011.0, 'Time played', 93757.0], ['Year:', 2012.0, 'Time played', 378296.0], ['Year:', 2013.0, 'Time played', 120306.0], ['Year:', 2014.0, 'Time played', 130452.0], ['Year:', 2015.0, 'Time played', 312238.0], ['Year:', 2016.0, 'Time played', 29298.0], ['Year:', 2017.0, 'Time played', 43327.0]]

In [ ]:
def PlayTimeGenre(genre: str):

    total_hours_action = combined_df[combined_df['Action'] == 1]['playtime_forever'].sum()

In [153]:
playtime_db2=playtime_db1.drop('user_id',axis=1)
playtime_db2

        release_year  playtime_forever
468642        1993.0               0.0
468643        1995.0             217.0
468644        1996.0               0.0
468645        1998.0               0.0
468646        1999.0              44.0
468647        2000.0           70644.0
468648        2001.0              13.0
468649        2002.0             238.0
468650        2003.0            7673.0
468651        2004.0          127411.0
468652        2005.0           21339.0
468653        2006.0             896.0
468654        2007.0          112784.0
468655        2008.0             224.0
468656        2009.0          108326.0
468657        2010.0           78083.0
468658        2011.0           93757.0
468659        2012.0          378296.0
468660        2013.0          120306.0
468661        2014.0          130452.0
468662        2015.0          312238.0
468663        2016.0           29298.0
468664        2017.0           43327.0

In [163]:
listtime=[]
for i, row in playtime_db1.iterrows(): 
    listtime.append(['Year:', row['release_year'],'Time played', row['playtime_forever']])

In [167]:
reviews

,user_id,item_id,recommend,review,year,sentiment_analysis
0,76561197970982479,1250,True,Simple yet with great replayability. In my opi...,2011,2
1,76561197970982479,22200,True,It's unique and worth a playthrough.,2011,2
2,76561197970982479,43110,True,Great atmosphere. The gunplay can be a bit chu...,2011,2
3,js41637,251610,True,I know what you think when you see this title ...,2014,2
4,js41637,227300,True,For a simple (it's actually not all that simpl...,2013,2
...,...,...,...,...,...,...
49181,wayfeng,730,True,its FUNNNNNNNN,2015,2
49182,76561198251004808,253980,True,Awesome fantasy game if you don't mind the gra...,2015,2
49183,72947282842,730,True,Prettyy Mad Game,2015,0
49184,ApxLGhost,730,True,AMAZING GAME 10/10,2015,2
49185,76561198267374962,369200,True,Why I voted yes? 1. Girl characters have boobs...,2015,2

In [243]:
year=2012
reviews_f=reviews[(reviews['year']== year)&((reviews['sentiment_analysis']==1)|(reviews['sentiment_analysis']==2))&(reviews['recommend']==True)]
reviews_fr=reviews_f.groupby('item_id')['recommend'].sum().reset_index()

In [208]:
reviews_fr=reviews_f.groupby('item_id')['recommend'].sum().reset_index()
reviews_fr.sort_values(by='recommend',ascending=False).head(3)
alldbgames=alldb.drop_duplicates(subset='title')
alldbgames.drop(['release_year''user_id','playtime_forever','Action','Adventure','Audio Production','Early Access','Photo Editing','RPG','Racing','Simulation','Software Training','Sports','Web Publishing','Utilities','Strategy','Video Production','Casual','Animation &amp; Modeling','Design &amp; Illustration','Education','Free to Play','Indie','Design &amp; Illustration','Massively Multiplayer'],axis=1,inplace=True)
alldbgames.reset_index(inplace=True)
alldbgames.drop('index',axis=True,inplace=True)
alldbgames.to_csv('steam_games_devel.csv')

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16780\1971415095.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alldbgames.drop(['user_id','playtime_forever','Action','Adventure','Audio Production','Photo Editing','RPG','Racing','Simulation','Software Training','Sports','Web Publishing','Utilities','Strategy','Video Production'],axis=1,inplace=True)

In [9]:
alldbgames=alldb.drop_duplicates(subset='title')
alldbgames.drop(['release_year','user_id','playtime_forever','Action','Adventure','Audio Production','Early Access','Photo Editing','RPG','Racing','Simulation','Software Training','Sports','Web Publishing','Utilities','Strategy','Video Production','Casual','Animation &amp; Modeling','Design &amp; Illustration','Education','Free to Play','Indie','Design &amp; Illustration','Massively Multiplayer'],axis=1,inplace=True)
alldbgames.reset_index(inplace=True)
alldbgames.drop('index',axis=True,inplace=True)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_1080\3831990937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alldbgames.drop(['release_year','user_id','playtime_forever','Action','Adventure','Audio Production','Early Access','Photo Editing','RPG','Racing','Simulation','Software Training','Sports','Web Publishing','Utilities','Strategy','Video Production','Casual','Animation &amp; Modeling','Design &amp; Illustration','Education','Free to Play','Indie','Design &amp; Illustration','Massively Multiplayer'],axis=1,inplace=True)
C:\Users\Usuario\AppData\Local\Temp\ipykernel_1080\3831990937.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alldbgames.drop('index',axis=True,inplace=True)

In [10]:
alldbgames

,title,id,developer
0,Counter-Strike,10.0,Valve
1,Team Fortress Classic,20.0,Valve
2,Day of Defeat,30.0,Valve
3,Deathmatch Classic,40.0,Valve
4,Half-Life: Opposing Force,50.0,Gearbox Software
...,...,...,...
8260,DUCATI - 90th Anniversary,456780.0,Milestone S.r.l.
8261,Mimpi Dreams,444770.0,Silicon Jelly
8262,NOBUNAGA'S AMBITION: Sphere of Influence - Asc...,375450.0,"KOEI TECMO GAMES CO., LTD."
8263,ChaosTower,354280.0,CashcowGames
8264,Aveyond 4: Shadow of the Mist,433920.0,"Amaranth Games, LLC"

In [244]:
merged_df=pd.merge(alldbgames,reviews_fr,right_on='item_id',left_on='id')

In [253]:
search=merged_df.sort_values(by='recommend',ascending=False).head(3)
most_rec_titles=search['title'].tolist()
print(f'The most recomended games for the year {year}, were: \n 1st: {most_rec_titles[0]}\n 2nd: {most_rec_titles[1]}\n 3rd: {most_rec_titles[2]}')

The most recomended games for the year 2012, were:
 1st: Terraria
 2nd: Garry's Mod
 3rd: Left 4 Dead 2

In [12]:
year=2012
reviews_f=reviews[(reviews['year']== year)&(reviews['sentiment_analysis']==0)&(reviews['recommend']==False)]
reviews_fr=reviews_f.groupby('item_id')['recommend'].count().reset_index()
merged_df=pd.merge(alldbgames,reviews_fr,right_on='item_id',left_on='id')
search=merged_df.groupby('developer')['recommend'].sum().reset_index().sort_values(by='recommend',ascending=False)
least_recom_developers=search['developer'].tolist()
print(f'The least recomended developers for the year {year}, were: \n 1st: {least_recom_developers[0]}\n 2nd: {least_recom_developers[1]}\n 3rd: {least_recom_developers[2]}')

The least recomended developers for the year 2012, were:
 1st: NeoCoreGames
 2nd: Slant Six Games
 3rd: Treyarch

In [301]:
developer='Facepunch Studios'
merged_df=pd.merge(alldbgames,reviews,right_on='item_id',left_on='id')
merged_df.head()
#search1=merged_df.groupby('sentiment_analysis')['developer'].count().reset_index()
#search1
#search1=merged_df.groupby('developer')['sentiment_analysis'].count().reset_index()
#search1

,title,id,developer,user_id,item_id,recommend,review,year,sentiment_analysis
0,Counter-Strike,10.0,Valve,Bennysaputra,10,True,Cool game,2015,2
1,Counter-Strike,10.0,Valve,Monsta45,10,True,Wallbang simulator,2015,2
2,Counter-Strike,10.0,Valve,76561198040188061,10,True,this game is the 1# online action game is awes...,2011,2
3,Counter-Strike,10.0,Valve,mayshowganmore,10,True,THE BEST FPS GAME!!!!!,2014,2
4,Counter-Strike,10.0,Valve,BestinTheWorldThund3r,10,True,One of the best childhood games i have ever pl...,2014,2

In [302]:
valve_reviews = merged_df[merged_df['developer'] == developer]
positive_count = len(valve_reviews[valve_reviews['sentiment_analysis'] == 2])
neutral_count = len(valve_reviews[valve_reviews['sentiment_analysis'] == 1])
negative_count = len(valve_reviews[valve_reviews['sentiment_analysis'] == 0])

results_dict = {
    developer: {
        'Negative': negative_count,
        'Neutral': neutral_count,
        'Positive': positive_count
    }
}
print(results_dict)

{'Facepunch Studios': {'Negative': 290, 'Neutral': 0, 'Positive': 1969}}

In [3]:
maindb=pd.read_csv('maindb.csv')

In [5]:
maindb.head()

,user_id,playtime_forever,title,id,developer,release_year,Action,Adventure,Animation &amp; Modeling,Audio Production,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,76561197970982479,6.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,js41637,0.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Riot-Punch,0.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,doctr,93.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,corrupted_soul,108.0,Counter-Strike,10.0,Valve,2000.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
maindb1=maindb.head(2000000)

In [9]:
maindb1.to_csv('maindb1.csv')

In [12]:
maindb2=maindb1.head(800000)
maindb2.to_csv('maindb2.csv')

In [27]:
maindb4=maindb.head(300000)

In [28]:
maindb4.to_csv('maindb4.csv')